plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ai.assistance.shower'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ai.assistance.shower'
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        aidl true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
