cmake_minimum_required(VERSION 3.22.1)
project(launcher_node)
add_library(node SHARED IMPORTED)
set_target_properties(node PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/../jniLibs/${ANDROID_ABI}/libnode.so)
add_library(launcher_node SHARED node_bridge.cpp)
target_include_directories(launcher_node PRIVATE node-include)
target_link_libraries(launcher_node node log)
